
name: Azure Deploy SSH

on:
  push:
    branches: [ deployment ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v2
      
      - name: build-nextjs
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build
      
      - name: commit-to-deployment
        uses: EndBug/add-and-commit@v6
        with:
          author_name: Aniket Biprojit Chowhdury
          author_email: aniket_chowdhury@hotmail.com
          branch: deployment
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: ssh-and-deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USER_NAME }}
          port: 22
          host: ${{ secrets.HOST_NAME }}
          script: |
            source /home/azureuser/.bashrc
            cd /home/azureuser/public/deployments/BrainBrush-Frontend
            ls -la
            # git checkout deployment
            git pull
            /home/azureuser/.nvm/versions/node/v14.15.4/bin/node /home/azureuser/.nvm/versions/node/v14.15.4/bin/pm2 restart brainbrush_frontend_3003
