
name: Azure Deploy SSH

on:
  push:
    branches: [ deployment ]
  pull_request:
    branches: [ deployment ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  echo:
    runs-on: ubuntu-latest
    steps:

      # Runs a single command using the runners shell
      - name: ssh-and-deploy
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_KEY }}
          username: ${{ secrets.USER_NAME }}
          port: 22
          host: ${{ secrets.HOST_NAME }}
          script: whoami
